-- MySQL Script generated by MySQL Workbench
-- 04/10/15 18:53:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vraenchike_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vraenchike_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vraenchike_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `vraenchike_db` ;

-- -----------------------------------------------------
-- Table `vraenchike_db`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vraenchike_db`.`Photo` (
  `idPhoto` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(150) NULL,
  `Likes` INT NULL,
  `Dislike` INT NULL,
  PRIMARY KEY (`idPhoto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vraenchike_db`.`Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vraenchike_db`.`Place` (
  `idPlace` INT NOT NULL AUTO_INCREMENT,
  `lng` DOUBLE NULL,
  `lat` DOUBLE NULL,
  `radius` INT NULL,
  PRIMARY KEY (`idPlace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vraenchike_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vraenchike_db`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `lastPhotoView` DATETIME NULL,
  `user_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vraenchike_db`.`UserLoginInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vraenchike_db`.`UserLoginInfo` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(120) NULL,
  `pass` VARCHAR(120) NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `FKUSR` FOREIGN KEY (`idUser`) REFERENCES `User` (`idUser`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `vraenchike_db`.`UserPhoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vraenchike_db`.`UserPhoto` (
  `idUserPhoto` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idPhoto` INT NOT NULL,
  `Photo_idPhoto` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUserPhoto`, `Photo_idPhoto`),
  INDEX `fk_UserPhoto_Photo1_idx` (`Photo_idPhoto` ASC),
  INDEX `fk_UserPhoto_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_UserPhoto_Photo1`
    FOREIGN KEY (`Photo_idPhoto`)
    REFERENCES `vraenchike_db`.`Photo` (`idPhoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserPhoto_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `vraenchike_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vraenchike_db`.`Banned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vraenchike_db`.`Banned` (
  `idBanned` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(145) NULL,
  PRIMARY KEY (`idBanned`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vraenchike_db`.`UserPlaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vraenchike_db`.`UserPlaces` (
  `idUserPlaces` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idPlace` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  `Place_idPlace` INT NOT NULL,
  PRIMARY KEY (`idUserPlaces`, `User_idUser`, `Place_idPlace`),
  INDEX `fk_UserPlaces_User_idx` (`User_idUser` ASC),
  INDEX `fk_UserPlaces_Place1_idx` (`Place_idPlace` ASC),
  CONSTRAINT `fk_UserPlaces_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `vraenchike_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserPlaces_Place1`
    FOREIGN KEY (`Place_idPlace`)
    REFERENCES `vraenchike_db`.`Place` (`idPlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vraenchike_db`.`UserBanned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vraenchike_db`.`UserBanned` (
  `idUserBanned` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idBanned` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Banned_idBanned` INT NOT NULL,
  PRIMARY KEY (`idUserBanned`),
  INDEX `fk_UserBanned_User1_idx` (`User_idUser` ASC),
  INDEX `fk_UserBanned_Banned1_idx` (`Banned_idBanned` ASC),
  CONSTRAINT `fk_UserBanned_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `vraenchike_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserBanned_Banned1`
    FOREIGN KEY (`Banned_idBanned`)
    REFERENCES `vraenchike_db`.`Banned` (`idBanned`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
